### ISSUE TITLE
Is there a reason we map specific code systems from oid to uri?

### ISSUE THREAD

**Issue by SomethingSexy** [cqframework/cql-exec-vsac#30]
Specifically looking at src/svs.js line 60-73, if we a code system from the list in this repo, we update the system to be the uri instead of the oid? Is there a functional reason for this?

Is it possible to include both? Keep the urn:oid and also add the uri side by side?

We have cases where we are receiving the codes as the urn:oid and I would rather not update the source data.

**Comment by cmoesel** [comment]
The VSAC FHIR API always returns codes using the canonical URL of the code system. When we use the SVS API, we convert OIDs to URLs in an attempt to normalize the output so that you have similar results whether doing expansions via the SVS API or the FHIR API.

We also do this because, at least in the FHIR ecosystem, using the system URL for common systems is greatly preferred over using `urn:oid` variant. For example, the [Using CQL with FHIR IG](https://build.fhir.org/ig/HL7/cql-ig/using-cql.html#code-systems) specifies that code system identifiers MUST be the canonical URL of the system. The [FHIR spec](https://hl7.org/fhir/R5/terminologies-systems.html#4.3.0) says:
> For URIs specified here for code systems defined as part of FHIR, they SHALL be used in preference to any other identifying mechanisms.

As a result, FHIR data fed into the CQL engine usually uses the system URLs in its codes, so using the URLs in the Value Set cache (instead of OIDs) improves the matching.

That said, it sounds like you have a case where this is _not_ what you want. I wouldn't want to change the default behavior from what it is now, but I'd be open to a PR that adds support for a configuration parameter that allows you to indicate if you'd prefer the OIDs, or even to allow for codes to be put in the cache using both URL and OID.

**Comment by SomethingSexy** [comment]
@cmoesel  that makes sense, thank you for the clarification.  Yeah unfortunately in our situation we are receiving data from thousands of sources and it isn't always possible to direct them to use the uri.  

I appreciate you accepting PR though! I will take a look a solution over the next week or so and submit a PR to make it configurable.
